In [1]:
#Autograd package do all kinds of optimization
# Calculating gradients in pytorch
import torch

In [5]:
x = torch.rand(3, requires_grad=True)
print(x)

tensor([0.8052, 0.7990, 0.0699], requires_grad=True)


In [8]:
# Pytorch creates computational graph
y = x+2
# We have added the backward add propagation to the function
print(y)

tensor([2.8052, 2.7990, 2.0699], grad_fn=<AddBackward0>)


![alt text](add.png)

In [9]:
# We can do multiplication as well mean function
z = y*y*2
print(z)
z = z.mean()
print(z)

tensor([15.7380, 15.6686,  8.5688], grad_fn=<MulBackward0>)
tensor(13.3251, grad_fn=<MeanBackward0>)


In [10]:
# When  we calculate gradient of z w.r.t x
z.backward() # dz/dx
print(x.grad)



tensor([3.7402, 3.7320, 2.7598])
