In [16]:
from numpy import double, float64
import torch
import numpy as np

In [2]:
x = torch.empty(3)
y = torch.empty(2,3)
z = torch.rand(2,3)
a = torch.empty(2,3)
b = torch.ones(2,3)
c = torch.ones(2,4, dtype=torch.int)
d = torch.empty(2,3,dtype=torch.double)
e = torch.empty(2,4,dtype=torch.float64)

In [3]:
#Another way of creating a tensor
f = torch.tensor([1.2,3.3,1.9])


In [4]:
print(x,y,z,a,b,c,d,e,f)

tensor([2.2275e+08, 4.5897e-41, 2.1947e+15]) tensor([[2.0750e+17, 4.5898e-41, 2.0750e+17],
        [4.5898e-41, 0.0000e+00, 0.0000e+00]]) tensor([[3.9525e-01, 9.8288e-01, 8.4716e-01],
        [2.9068e-01, 1.8829e-04, 3.6940e-01]]) tensor([[1.4013e-45, 0.0000e+00, 4.9689e-37],
        [3.0861e-41, 1.4013e-45, 0.0000e+00]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32) tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [6.9505e-310, 6.9505e-310,  0.0000e+00]], dtype=torch.float64) tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, 6.9505e-310]],
       dtype=torch.float64) tensor([1.2000, 3.3000, 1.9000])


In [5]:
print(type(f))

<class 'torch.Tensor'>


In [6]:
sumed = y+z
print(y)
print(z)
print(sumed)

tensor([[2.0750e+17, 4.5898e-41, 2.0750e+17],
        [4.5898e-41, 0.0000e+00, 0.0000e+00]])
tensor([[3.9525e-01, 9.8288e-01, 8.4716e-01],
        [2.9068e-01, 1.8829e-04, 3.6940e-01]])
tensor([[2.0750e+17, 9.8288e-01, 2.0750e+17],
        [2.9068e-01, 1.8829e-04, 3.6940e-01]])


In [7]:
sumed = torch.add(y,z)
print(sumed)

tensor([[2.0750e+17, 9.8288e-01, 2.0750e+17],
        [2.9068e-01, 1.8829e-04, 3.6940e-01]])


In [8]:
# all python function with preceding underscore (_) willl do inplace operation
y.add_(x)
print(y)

tensor([[2.0750e+17, 9.1795e-41, 2.0969e+17],
        [2.2275e+08, 4.5897e-41, 2.1947e+15]])


In [9]:
subtract = x-y
print(subtract)


tensor([[-2.0750e+17, -4.5898e-41, -2.0750e+17],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [10]:
subtract = torch.sub(x,y)
print(subtract)

tensor([[-2.0750e+17, -4.5898e-41, -2.0750e+17],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [11]:
mult = x*y
print(mult)

tensor([[4.6220e+25, 0.0000e+00, 4.6021e+32],
        [4.9617e+16, 0.0000e+00, 4.8165e+30]])


In [13]:
mult = torch.mul(x,y)
print(mult)

tensor([[4.6220e+25, 0.0000e+00, 4.6021e+32],
        [4.9617e+16, 0.0000e+00, 4.8165e+30]])


In [14]:
y.mul_(x)

tensor([[4.6220e+25, 0.0000e+00, 4.6021e+32],
        [4.9617e+16, 0.0000e+00, 4.8165e+30]])

In [15]:
div = x/y
print(div)

tensor([[4.8193e-18,        inf, 4.7689e-18],
        [4.4894e-09,        inf, 4.5565e-16]])


In [18]:
a = torch.ones(6)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
