In [1]:
import torch
import torch.nn as nn

In [9]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(32,16)
        self.layer2 = nn.Linear(16,8)
        self.layer3 = nn.Linear(8,1)
    
    def forward(self, features):
        x = self.layer1(features)
        x = self.layer2(x)
        x = self.layer3(x)
        return x

In [10]:
model = Model()
features = torch.rand((2,32))
print(features)

tensor([[0.2643, 0.9763, 0.6407, 0.9856, 0.1218, 0.5395, 0.0255, 0.5600, 0.9109,
         0.9722, 0.3745, 0.7751, 0.0821, 0.4974, 0.7012, 0.9365, 0.3746, 0.0316,
         0.0079, 0.5378, 0.6441, 0.6358, 0.4599, 0.3618, 0.0155, 0.8466, 0.7565,
         0.0708, 0.6720, 0.6560, 0.9509, 0.4045],
        [0.1486, 0.9002, 0.7665, 0.5186, 0.6512, 0.6841, 0.2698, 0.1902, 0.0402,
         0.3001, 0.5973, 0.5280, 0.3791, 0.6134, 0.6606, 0.9587, 0.4318, 0.3112,
         0.3498, 0.7472, 0.6174, 0.8943, 0.0318, 0.6900, 0.8017, 0.7721, 0.3962,
         0.0181, 0.9398, 0.2214, 0.3884, 0.1153]])


In [11]:
# We pass the 2 inputs (at a time one input) of 128 features into the model and the model output two predicted value.
model(features)

tensor([[0.0602],
        [0.0838]], grad_fn=<AddmmBackward0>)

![alt text](nn.svg)

In [14]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.base = nn.Sequential(
                    nn.Linear(32,16),
                    nn.Linear(16,8),
                    nn.Linear(8,1)
                    )
    
    def forward(self, features):
        x = self.base(features)
        return x

In [15]:
model = Model()
features = torch.rand((3,32))
model(features)

tensor([[0.0129],
        [0.0544],
        [0.0243]], grad_fn=<AddmmBackward0>)