In [1]:
import torch
import torchvision

In [2]:
resnet18 = torchvision.models.resnet18(pretrained=True)
resnet18.eval()
example_inputs = torch.rand(1, 3, 224, 224)
resnet18_traced = torch.jit.trace(resnet18, example_inputs = example_inputs)
resnet18_traced.save("/home/manojkl/Documents/Master_thesis/Code/Tutorial_code/resnet18_traced.pt")

In [4]:
import numpy as np
from numpy.linalg import inv

In [8]:
a = np.array([[1, 3, 2, 2], [3, 1, 1, 4],[1, 2, 2, 5],[1, 2, 2, 5]])
b = np.array([[5, 6, 6, 8], [2, 2, 2, 8],[6, 6, 2, 8],[2, 3, 6, 7]])

rel_pose = np.dot(a, inv(b))

print(a)
print(b)
print(inv(b))
print(rel_pose)

[[1 3 2 2]
 [3 1 1 4]
 [1 2 2 5]
 [1 2 2 5]]
[[5 6 6 8]
 [2 2 2 8]
 [6 6 2 8]
 [2 3 6 7]]
[[-17.    -9.    12.    16.  ]
 [ 17.     8.75 -11.75 -16.  ]
 [ -4.    -2.25   2.75   4.  ]
 [  1.     0.75  -0.75  -1.  ]]
[[ 28.    14.25 -19.25 -26.  ]
 [-34.   -17.5   24.    32.  ]
 [ 14.     7.75  -9.75 -13.  ]
 [ 14.     7.75  -9.75 -13.  ]]


In [9]:
np.matrix.trace(a)

9

In [10]:
R = rel_pose[:3, :3]
t = rel_pose[:3, 3]
print(R)
print(t)

[[ 28.    14.25 -19.25]
 [-34.   -17.5   24.  ]
 [ 14.     7.75  -9.75]]
[-26.  32. -13.]


In [13]:
np.linalg.norm(t)

43.23193264243474