In [33]:
# see load_label_png.py also.
import numpy as np
import PIL.Image
import imageio
import os
import csv

In [15]:
# label_png = '/home/latai/Documents/Master_thesis_v2/data/test3/label/0.png'
label_png = '/home/latai/Documents/Master_thesis_v2/data/test3/label/0.png'
lbl = np.asarray(PIL.Image.open(label_png))
print(lbl.dtype)
print(np.unique(lbl))
print(lbl.shape)

int32
[ 0  1  3  4  7  9 21]
(968, 1296)


In [ ]:
[ 0  1  3  4  7  9 21]

In [17]:
label_png = '/home/latai/Documents/Master_thesis_v2/data/test3/0.png'
lbl = np.asarray(PIL.Image.open(label_png))
print(lbl.dtype)
print(np.unique(lbl))
print(lbl.shape)

uint8
[ 0  1  2  3  7 14 16]
(240, 320)


In [ ]:
# Example script to convert label images from the *_2d-label.zip or *_2d-label-filt.zip data for each scan.
# Note: already preprocessed data for a set of frames subsampled from the full datasets is available to download through the ScanNet download.
# Input:
#   - path to label image to convert
#   - label mapping file (scannetv2-labels.combined.tsv)
#   - output image file
# Outputs the label image with nyu40 labels as an 8-bit image 
#
# example usage: convert_scannet_label_image.py --input_file [path to input label image] --label_map_file [path to scannet-labels.combined.tsv] --output_file [output image file]
# (see util.visualize_label_image() for producing a colored visualization)


# python imports
import math
import os, sys, argparse
import inspect

try:
    import numpy as np
except:
    print "Failed to import numpy package."
    sys.exit(-1)
try:
    import imageio
except:
    print("Please install the module 'imageio' for image processing, e.g.")
    print("pip install imageio")
    sys.exit(-1)

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)
import util

parser = argparse.ArgumentParser()
parser.add_argument('--input_file', required=True, help='path to input label image')
parser.add_argument('--label_map_file', required=True, help='path to scannetv2-labels.combined.tsv')
parser.add_argument('--output_file', required=True, help='output image file')
opt = parser.parse_args()


def map_label_image(image, label_mapping):
    mapped = np.copy(image)
    for k,v in label_mapping.iteritems():
        mapped[image==k] = v
    return mapped.astype(np.uint8)


def main():
    image = np.array(imageio.imread(opt.input_file))
    label_map = util.read_label_mapping(opt.label_map_file, label_from='id', label_to='nyu40id')
    mapped_image = map_label_image(image, label_map)
    imageio.imwrite(opt.output_file, mapped_image)
    # uncomment to save out visualization
    # util.visualize_label_image(os.path.splitext(opt.output_file)[0] + '_vis.jpg', mapped_image)


if __name__ == '__main__':
    main()

In [52]:
def map_label_image(image, label_mapping):
    mapped = np.copy(image)
    for k,v in label_mapping.items():
        mapped[image==k] = v
    return mapped.astype(np.uint8)


def main(input_file,label_map_file, output_file ):
    image = np.array(imageio.imread(input_file))
    label_map = read_label_mapping(label_map_file, label_from='id', label_to='nyu40id')
    mapped_image = map_label_image(image, label_map)
    imageio.imwrite(output_file, mapped_image)
    visualize_label_image(os.path.splitext(output_file)[0] + '_vis.jpg', mapped_image)

In [53]:
# if string s represents an int
def represents_int(s):
    try: 
        int(s)
        return True
    except ValueError:
        return 
    
def read_label_mapping(filename, label_from='raw_category', label_to='nyu40id'):
    assert os.path.isfile(filename)
    mapping = dict()
    with open(filename) as csvfile:
        reader = csv.DictReader(csvfile, delimiter='\t')
#         print(reader)
        for row in reader:
#             print(row)
            mapping[row[label_from]] = int(row[label_to])
    # if ints convert 
#     print(mapping.keys()[0])
    if represents_int(list(mapping.keys())[0]):
        mapping = {int(k):v for k,v in mapping.items()}
    return mapping

# color by label
def visualize_label_image(filename, image):
    height = image.shape[0]
    width = image.shape[1]
    vis_image = np.zeros([height, width, 3], dtype=np.uint8)
    color_palette = create_color_palette()
    for idx, color in enumerate(color_palette):
        vis_image[image==idx] = color
    imageio.imwrite(filename, vis_image)

# color palette for nyu40 labels
def create_color_palette():
    return [
       (0, 0, 0),
       (174, 199, 232),
       (152, 223, 138),
       (31, 119, 180), 
       (255, 187, 120),
       (188, 189, 34), 
       (140, 86, 75),  
       (255, 152, 150),
       (214, 39, 40),  
       (197, 176, 213),
       (148, 103, 189),
       (196, 156, 148),
       (23, 190, 207),
       (178, 76, 76),  
       (247, 182, 210),
       (66, 188, 102), 
       (219, 219, 141),
       (140, 57, 197), 
       (202, 185, 52), 
       (51, 176, 203), 
       (200, 54, 131), 
       (92, 193, 61),  
       (78, 71, 183),  
       (172, 114, 82), 
       (255, 127, 14), 
       (91, 163, 138), 
       (153, 98, 156), 
       (140, 153, 101),
       (158, 218, 229),
       (100, 125, 154),
       (178, 127, 135),
       (120, 185, 128),
       (146, 111, 194),
       (44, 160, 44),  
       (112, 128, 144),
       (96, 207, 209), 
       (227, 119, 194),
       (213, 92, 176), 
       (94, 106, 211), 
       (82, 84, 163),
       (100, 85, 144)
    ]

In [54]:
label_png = '/home/latai/Documents/Master_thesis_v2/data/test3/0.png'
label_map_file = '/home/latai/Documents/Master_thesis_v2/data/test3/scannetv2-labels.combined.tsv'
output_file = '/home/latai/Documents/Master_thesis_v2/data/test3/out.png'
main(label_png, label_map_file, output_file)

/home/latai/anaconda3/envs/latai/lib/python3.7/site-packages/ipykernel_launcher.py:9: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning dissapear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  if __name__ == '__main__':
